name: dart_application
description: Made by DONski LIVE
version: 1.0.0

environment:
  sdk: '>=2.15.1 <3.0.0'

dependencies:
  angular: ^7.0.2
  angular_bloc: ^8.0.0
  angular_forms: ^4.0.1
  http: ^0.13.4
  firebase: ^9.0.2
  html: ^0.15.0
  js: ^0.6.3

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
